coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: 'reach,diff,flags,tree'
  behavior: default
  require_changes: false

ignore:
  - '**/*.stories.tsx'
  - '**/*.stories.ts'
  - '**/*.config.js'
  - '**/*.config.ts'
  - '**/*.config.mjs'
  - '**/index.ts'
  - 'src/index.ts'
  - 'dist/'
  - 'website/'
  - 'storybook-static/'
  - '.storybook/'
  - 'vitest.setup.ts'
