name: 📚 Documentation Issue
description: Report an issue with documentation or suggest improvements
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please provide details about the documentation issue or improvement.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation is this about?
      options:
        - Component Documentation
        - API Reference
        - Getting Started Guide
        - Installation Instructions
        - Examples/Tutorials
        - Storybook Stories
        - README
        - Contributing Guide
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of documentation issue is this?
      options:
        - Missing Documentation
        - Incorrect Information
        - Outdated Content
        - Unclear Instructions
        - Broken Links
        - Typo/Grammar
        - Improvement Suggestion
        - New Documentation Request
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is this documentation located? (URL, file path, or component name)
      placeholder: e.g., https://buildgrid-ui.dev/docs/button, src/components/Button/README.md
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: What does the current documentation say? (copy/paste the relevant section)
      placeholder: Paste the current documentation content here...

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the problem with the current documentation or what's missing.
      placeholder: Clearly describe what's wrong or missing...
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved? What should it say instead?
      placeholder: Provide your suggested improvement or new content...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        Provide any additional context that would help us understand the issue.
        - What were you trying to accomplish?
        - What confused you?
        - What would have made it clearer?
      placeholder: Any additional context that would be helpful...

  - type: checkboxes
    id: audience
    attributes:
      label: Target Audience
      description: Who would benefit from this documentation improvement?
      options:
        - label: New users getting started
        - label: Experienced developers
        - label: Contributors to the project
        - label: Designers using the components
        - label: Maintainers and reviewers

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help improve this documentation?
      options:
        - label: I can submit a PR to fix this
        - label: I can help review proposed changes
        - label: I can provide additional examples
        - label: I can help with proofreading

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true