// Auto-generated file - DO NOT EDIT MANUALLY
// Generated by scripts/update-blog-posts.js
// Last updated: 2025-12-29T20:59:12.217Z

export interface BlogPost {
	id: string
	title: string
	description: string
	date: string
	permalink: string
	image: string | null
	tags: string[]
	author: {
		name: string
		imageURL: string
	}
}

export const LATEST_BLOG_POSTS: BlogPost[] = [
  {
    "id": "contributing-to-open-source",
    "title": "Why Contributing to Open Source Will Make You a Better Developer",
    "description": "Learn why contributing to open source will make you a better developer and how you can start with BuildGrid UI.",
    "date": "2025-12-29",
    "permalink": "/blog/contributing-to-open-source",
    "image": "/buildgrid-ui/img/blog/open-source-contributions.png",
    "tags": [
      "open-source",
      "react",
      "typescript",
      "community"
    ],
    "author": {
      "name": "Adriano Maringolo",
      "imageURL": "https://github.com/adrianomaringolo.png"
    }
  },
  {
    "id": "introducing-buildgrid-ui",
    "title": "Introducing BuildGrid UI - A Modern React Component Library",
    "description": "Today, I'm excited to announce the public release of BuildGrid UI - a comprehensive React component library that I've been developing throughout 2024 and 2025. This marks my first open-source project, and I'm thrilled to share it with the developer community.",
    "date": "2025-12-20",
    "permalink": "/blog/introducing-buildgrid-ui",
    "image": "/buildgrid-ui/img/blog/buildgrid-ui-launch.jpeg",
    "tags": [
      "launch",
      "react",
      "ui-library",
      "open-source",
      "typescript"
    ],
    "author": {
      "name": "Adriano Maringolo",
      "imageURL": "https://github.com/adrianomaringolo.png"
    }
  }
]

export const ALL_BLOG_POSTS: BlogPost[] = [
  {
    "id": "contributing-to-open-source",
    "title": "Why Contributing to Open Source Will Make You a Better Developer",
    "description": "Learn why contributing to open source will make you a better developer and how you can start with BuildGrid UI.",
    "date": "2025-12-29",
    "permalink": "/blog/contributing-to-open-source",
    "image": "/buildgrid-ui/img/blog/open-source-contributions.png",
    "tags": [
      "open-source",
      "react",
      "typescript",
      "community"
    ],
    "author": {
      "name": "Adriano Maringolo",
      "imageURL": "https://github.com/adrianomaringolo.png"
    }
  },
  {
    "id": "introducing-buildgrid-ui",
    "title": "Introducing BuildGrid UI - A Modern React Component Library",
    "description": "Today, I'm excited to announce the public release of BuildGrid UI - a comprehensive React component library that I've been developing throughout 2024 and 2025. This marks my first open-source project, and I'm thrilled to share it with the developer community.",
    "date": "2025-12-20",
    "permalink": "/blog/introducing-buildgrid-ui",
    "image": "/buildgrid-ui/img/blog/buildgrid-ui-launch.jpeg",
    "tags": [
      "launch",
      "react",
      "ui-library",
      "open-source",
      "typescript"
    ],
    "author": {
      "name": "Adriano Maringolo",
      "imageURL": "https://github.com/adrianomaringolo.png"
    }
  }
]
