import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
	tutorialSidebar: [
		'intro',
		{
			type: 'category',
			label: 'Components',
			items: [
				'components/accordion',
				'components/adaptive-input',
				'components/alert',
				'components/alert-dialog',
				'components/autocomplete',
				'components/avatar',
				'components/badge',
				'components/button',
				'components/calendar',
				'components/card',
				'components/carousel',
				'components/checkbox',
				'components/collapsible',
				'components/command',
				'components/currency-input',
				'components/dialog',
				'components/dropdown-menu',
				'components/html-text-area',
				'components/input',
				'components/label',
				'components/multi-select',
				'components/navigation-menu',
				'components/number-stepper',
				'components/pagination',
				'components/password-input',
				'components/popover',
				'components/progress',
				'components/radio-group',
				'components/search-bar',
				'components/select',
				'components/separator',
				'components/sheet',
				'components/skeleton',
				'components/slider',
				'components/spinner',
				'components/switch',
				'components/table',
				'components/tabs',
				'components/tag-input',
				'components/textarea',
				'components/toaster',
				'components/toggle',
				'components/toggle-group',
				'components/tooltip',
			],
		},
		{
			type: 'category',
			label: 'Blocks',
			items: [
				'blocks/bento-grid',
				'blocks/data-table',
				'blocks/empty-message',
				'blocks/file-upload-dropzone',
				'blocks/help-carousel',
				'blocks/html-text-editor',
				'blocks/lazy-image-gallery',
				'blocks/month-navigator',
				'blocks/navigable-list',
				'blocks/paginated-items',
				'blocks/pagination-controls',
				'blocks/sidebar',
			],
		},
		{
			type: 'category',
			label: 'Utilities',
			items: [
				{
					type: 'category',
					label: 'Formatters',
					items: [
						'utilities/formatters/currency',
						'utilities/formatters/date-formatters',
					],
				},
				{
					type: 'category',
					label: 'Hooks',
					items: [
						'utilities/hooks/use-copy-to-clipboard',
						'utilities/hooks/use-debounce',
						'utilities/hooks/use-local-storage',
					],
				},
				{
					type: 'category',
					label: 'Types',
					items: ['utilities/types/typescript-utilities'],
				},
			],
		},
	],
}

export default sidebars
