import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Components',
      items: [
        'components/accordion',
        'components/adaptive-input',
        'components/alert-dialog',
        'components/autocomplete',
        'components/avatar',
        'components/badge',
        'components/button',
        'components/calendar',
        'components/card',
        'components/checkbox',
        'components/command',
        'components/currency-input',
        'components/dialog',
        'components/dropdown-menu',
        'components/input',
        'components/label',
        'components/multi-select',
        'components/navigation-menu',
        'components/pagination',
        'components/password-input',
        'components/popover',
        'components/progress',
        'components/radio-group',
        'components/select',
        'components/separator',
        'components/skeleton',
        'components/spinner',
        'components/switch',
        'components/table',
        'components/tabs',
        'components/textarea',
        'components/toaster',
        'components/toggle',
        'components/toggle-group',
        'components/tooltip',
      ],
    },
    {
      type: 'category',
      label: 'Blocks',
      items: [
        'blocks/bento-grid',
        'blocks/data-table',
        'blocks/empty-message',
        'blocks/help-carousel',
        'blocks/html-text-editor',
        'blocks/lazy-image-gallery',
        'blocks/month-navigator',
        'blocks/navigable-list',
        'blocks/paginated-items',
        'blocks/pagination-controls',
        'blocks/sidebar',
      ],
    },
  ],
};

export default sidebars;